name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "00 7 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has had no activity in the last 30 days. If the stale label is not removed, the issue will be closed in 5 days.'
        stale-pr-message: 'This PR has had no activity in the last 30 days. If the stale label is not removed, the issue will be closed in 5 days.'
        stale-issue-label: 'status: stale'
        stale-pr-label: 'status: stale'
        days-before-stale: 30
        days-before-close: 5
